export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT";
export const SET_STORES = "SET_STORES";
export const EDIT_STORE = "EDIT_STORE"

export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const ADD_QUANTITY = "ADD_QUANTITY";
export const REDUCE_QUANTITY = "REDUCE_QUANTITY";
export const SET_SHOP_ITEMS = "SET_SHOP_ITEMS"
export const SET_SEARCHED_VALUE = "SET_SEARCHED_VALUE";
export const SET_LOCATION_FILTER = "SET_LOCATION_FILTER";
