export const LOGIN = "LOGIN"
export const onLogout = "onLogout"
export const SET_LOADING = "SET_LOADING"
export const EDIT_STORE = "EDIT_STORE"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const SET_SHOP_ITEMS = "SET_SHOP_ITEMS"
